In [ ]:
from sqlalchemy import create_engine
from datetime import date

USER = 'capstone'
PASSWORD = 'capstone'
HOST = 'localhost'
DATABASE = 'debt_management'

mariadb_connection_uri = f'mysql+pymysql://{USER}:{PASSWORD}@{HOST}/{DATABASE}'

engine = create_engine(mariadb_connection_uri, future=True)

In [182]:
from sqlalchemy import text

#FUNCTION for checking quantity available
def amount_of_debt(id_no): 
    with engine.connect() as conn:
        
        #GET the row that the id number corresponds to
        get_row = "SELECT * FROM accounts WHERE id="+str(id_no)
        get_row = conn.execute(text(get_row))
        row = get_row.fetchone() #https://stackoverflow.com/questions/13205157/just-one-row-from-sqlalchemy
        
        #GET quantity from the values in row
        debt = str(row[3]) 
        
        #GET name from the values in row
        name = str(row[1])
        
    return name+ " [id:" +str(id_no)+ "] currently has " +debt+ " in debt"

#FUNCTION for adding new accounts
def add_account(name, debt_amount):
    with engine.connect() as conn:
        
        #INSERT new account into table  #https://www.w3schools.com/sql/sql_insert.asp
        new = "INSERT INTO accounts (name, amount) VALUES ('" +name+ "'," +str(debt_amount)+ ");"
        new = conn.execute(text(new))
        
        conn.commit()
    
        #GET id_no
        get_row = "SELECT * FROM accounts WHERE name LIKE '%"+name+"%';"
        get_row = conn.execute(text(get_row))
        row = get_row.fetchone()
        
        id_no = str(row[0])
    
        conn.close()
        
        return "A new account has been made for " +name+ " [id:" +str(id_no)+ "] who currently has " +str(debt_amount)+ " in debt"

#FUNCTION for receiving payment, subtract to total debt
def receive_pay (id_no, name, amount_paid):
    with engine.connect() as conn:
        
        #Change values #https://www.w3schools.com/sql/sql_update.asp
        
        pay = "UPDATE accounts SET amount = amount -" +str(amount_paid)+ " WHERE name LIKE '%"+name+"%';"
        pay = conn.execute(text(pay))
        
        conn.commit()
        
        #GET current_balance
        get_row = "SELECT * FROM accounts WHERE name LIKE '%"+name+"%' AND id =" +str(id_no)+";"
        get_row = conn.execute(text(get_row))
        row = get_row.fetchone()
        current_balance = str(int(row[2]))
        
        return str(amount_paid)+ " was received from " +name+ " [id:" +str(id_no)+ "]. Current Debt Balance: " + current_balance

#FUNCTION for increasing debt
def increase_debt (id_no, name, debt_increase):
    with engine.connect() as conn:  
        
        #Change values #https://www.w3schools.com/sql/sql_update.asp
        inc = "UPDATE accounts SET amount = amount +" +str(debt_increase)+ " WHERE name LIKE '%"+name+"%' AND id =" +str(id_no)+ ";"
        inc = conn.execute(text(inc))
        
        conn.commit()
        
        #GET current_balance
        get_row = "SELECT * FROM accounts WHERE name LIKE '%"+name+"%' AND id =" +str(id_no)+";"
        get_row = conn.execute(text(get_row))
        row = get_row.fetchone()
        current_balance = str(int(row[2]))
        
        return str(debt_increase)+ " was added to the account of " +name+ " [id:" +str(id_no)+ "]. Current Debt Balance: " + current_balance
'''
NOT SURE ABOUT THIS PART

#FUNCTION for outputing current debts table
def current_debt_status():
    with engine.connect() as conn:
        
        #QUERY - all debts that are > than 0
        current = "SELECT * FROM accounts WHERE amount > 0"
        current = conn.execute(text(current))

#FUNCTION for outputing paid back debts table        
def debt_paid_back():
    with engine.connect() as conn:
        
        #QUERY - all debts that are = 0
        current = "SELECT * FROM accounts WHERE amount = 0"
        current = conn.execute(text(current))

#FUNCTION for outputing added debts
def additional_debt_incurred():
    with engine.connect() as conn:
'''       

#LIST for sql account names

with engine.connect() as conn: 
    
    name_list = []

    get_name_row = "SELECT * FROM accounts;"
    get_name_row = conn.execute(text(get_name_row))

    for row in get_name_row.fetchall(): #https://stackoverflow.com/questions/14835852/convert-sql-result-to-list-python
        name_list.append(row[1])
        
    #print(name_list)

#LIST for sql id

with engine.connect() as conn: 
    
    id_list = []

    get_id_row = "SELECT * FROM accounts;"
    get_id_row = conn.execute(text(get_id_row))

    for row in get_id_row.fetchall(): #https://stackoverflow.com/questions/14835852/convert-sql-result-to-list-python
        id_list.append(row[0])
        
    #print(id_list)